### ISSUE TITLE
peer review

### ISSUE THREAD

**Issue by AlexHamn** [Hamzaoutdoors/My_Portfolio#11]
Tuesday 20th morning session peer review.

**Comment by VictorOmarT** [comment]
Looks awesome!!

**Comment by AlexHamn** [comment]
![hamzaoutdoors_issues3](https://user-images.githubusercontent.com/81324033/126344782-08279642-6943-4c63-91ed-234dff68408b.jpg)

The welcome page repeats the background image on firefox.

**Comment by AlexHamn** [comment]
![hamzaoutdoors_issues2](https://user-images.githubusercontent.com/81324033/126344945-f08e2f1f-0be4-4996-b3b1-aaf9d7c98cf9.jpg)

There is no spacing between these two sections.

**Comment by AlexHamn** [comment]
![hamzaoutdoors_issues1](https://user-images.githubusercontent.com/81324033/126345111-6711550c-f58d-4dae-bcf0-19c1019e6bb4.jpg)

The background image does not go all the way to the right in this section.

**Comment by AlexHamn** [comment]
![hamzaoutdoors_issues4](https://user-images.githubusercontent.com/81324033/126345340-b78e6c11-9876-4422-8eea-ea433b9a6882.jpg)

On a vertical monitor, the project image and the text displace.
