### ISSUE TITLE
Morning session: Peer-to-peer code review

### ISSUE THREAD

**Issue by xJokeer** [Hamzaoutdoors/My_Portfolio#13]
Peer to peer  week 3

**Comment by xJokeer** [comment]
### Good job so far boy!
![cat on laptop](https://i.giphy.com/media/DhstvI3zZ598Nb1rFf/giphy.webp)

There's nothing to say!

**Comment by nelsinofrancisco** [comment]
# All good boy 💯 

- It's time to merge it 🕵️

**Comment by Hamzaoutdoors** [comment]
thanks, team for your feedbacks 👍
