### ISSUE TITLE
MODULE 1: FIRST MORNING SESSION ISSUE

### ISSUE THREAD

**Issue by Ntwali-Josue** [Hamzaoutdoors/My_Portfolio#3]
### Please work on these feedbacks: 

- In the mobile version of your portfolio, please work on the white space on the right side of your page.
- Please work on the min-width of your page, it seems to be a little bit high.

**Comment by Hamzaoutdoors** [comment]
# Hello Josh!
I've changed the min-width property, thanks for the feedback
